print("enter the number of days: ")
num = int(input())
year = int(num/365)
week = int((num%365)%7)
days = int((num%365)%7)
print("total number of years: ")
print(year)
print("total number of weeks: ")
print(week)
print("total number of days: ")
print(days)
